import { useState } from "react";
import Head from "next/head";
const PIX_KEY="casadosgatinhos22@gmail.com";
const WHATSAPP="5511991003113";
const INSTAGRAM="https://www.instagram.com/_casadosgatinhos";
const META_MENSAL=6880;
const MEMORIAL=[
{name:"Vitória",emoji:"👑",dates:"",story:"Sobreviveu a abuso humano e tiro de chumbinho. Resgatada, reabilitada, virou embaixadora da Casa. Ia a todos os eventos vestida a caráter, fazia fisioterapia regularmente. Paraplégica e guerreira. Símbolo de força e resiliência.",color:"#E8548C",cause:"Evoluiu a óbito após procedimento clínico — ausência de rastreamento de tratamento na clínica anterior."},
{name:"Sucrilhos",emoji:"🌟",dates:"",story:"Sucrilhos lutou bravamente contra a Panleucopenia, uma doença devastadora. Recebeu todo o carinho e cuidado que merecia. Não resistiu à doença, mas foi amado até o fim.",color:"#F4A460",cause:"Panleucopenia — evoluiu a óbito pela doença."},
{name:"Ozzy",emoji:"🎸",dates:"Dez/2025 – 13/Jan/2026",story:"Ozzy sempre foi muito carinhoso. Teve amor e carinho. A investigação de seu caso revelou falhas graves na clínica anterior.",color:"#9370DB",cause:"FeLV — ausência de rastreamento de tratamento identificada."},
{name:"Chico",emoji:"🍀",dates:"Dez/2025 – 12/Jan/2026",story:"Chico foi nosso pequeno guerreiro. Trouxe alegria e amor. Foi amado, querido e muito bem cuidado. A solicitação de prontuários revelou negligência e motivou a mudança de clínica. Descanse em paz, nossa pequena estrelinha.",color:"#2E8B57",cause:"FeLV — caso que motivou a intervenção e mudança de clínica."},
{name:"Bernardo",emoji:"💙",dates:"Faleceu 19/Jan/2026",story:"Bernardo foi um guerreiro. Lutou bravamente com uma doença tão ingrata. Partiu deixando uma saudade imensa em todos nós. Hoje o céu está mais brilhante, com você lá. Te amaremos para sempre.",color:"#6495ED",cause:"FIV — evoluiu a óbito sob cuidados."},
];
const RESIDENTS=[
{name:"Belinha",age:"15 anos",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"👵",foto:"https://lh3.googleusercontent.com/d/1Ys7rlqxnqs_tbYVQbKDsP1DJkjUyD0n-"},
{name:"Paçoca",age:"9 anos",sex:"M",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🍫",foto:"https://lh3.googleusercontent.com/d/1jnTezf5e2TnXiVeLcV0bEr8M7hz2otnU"},
{name:"Lua",age:"5 anos",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🌙",foto:"https://lh3.googleusercontent.com/d/18Kt06sdH2iHxYx5EQF8nQFd1aFEK9WV2"},
{name:"Lian",age:"5 anos",sex:"M",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🦁",foto:"https://lh3.googleusercontent.com/d/1Rkr5hzWFPik5g3u9SpFMyBjdUGoEUA1D"},
{name:"Gabi",age:"4 anos",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🌸",foto:"https://lh3.googleusercontent.com/d/1epdg8tKIm_-_GvoG2CM3PIY0X-HuWOXy"},
{name:"Tobby",age:"4 anos",sex:"M",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🐾",foto:""},
{name:"Melinda",age:"4 anos",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🎀",foto:""},
{name:"Fofucho",age:"4 anos",sex:"M",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🧸",foto:"https://lh3.googleusercontent.com/d/1s1ijtNER_hH1dUi_bAO4ZEVFYjJuFRn8"},
{name:"Adelly",age:"5 anos",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"💎",foto:"https://lh3.googleusercontent.com/d/1U8b3ZtMNKxQJKKZwocU12N73DSPh7Wzj"},
{name:"Ricky",age:"4 anos",sex:"M",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🎸",foto:"https://lh3.googleusercontent.com/d/163mFrBf44l2wQgBIPHjGM3lmryj-BBor"},
{name:"Ruan",age:"4 anos",sex:"M",castrated:true,vaccines:"V4+AR",condition:"",emoji:"⚽",foto:"https://lh3.googleusercontent.com/d/1ys47woaBiKiR0aTUIoQJqZ43UI-s5YKc"},
{name:"Layla",age:"2 anos",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🌺",foto:"https://lh3.googleusercontent.com/d/1N0Ud-n3_rkIOxsjZImRRuEvcSNIVMz06"},
{name:"Napoleão",age:"4 anos",sex:"M",castrated:true,vaccines:"V4+AR",condition:"",emoji:"👑",foto:"https://lh3.googleusercontent.com/d/1jx9-nromgqeWU6mcrlJM9zvZ6cbmocqU"},
{name:"Selena",age:"4 anos",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"⭐",foto:"https://lh3.googleusercontent.com/d/1HNX6anwBJKNQpicXVR9rpo0a1K-Wh_6A"},
{name:"Cristal",age:"3 anos",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"💠",foto:""},
{name:"Leo",age:"3 anos",sex:"M",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🦁",foto:"https://lh3.googleusercontent.com/d/1wkYYdDvPv-BlXYfd-U34MOnm3ZDuvgQ5"},
{name:"Evora",age:"3 anos",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🏰",foto:"https://lh3.googleusercontent.com/d/1HUgBTYhCM-AWkyICtNWDeXpQ0ofEXe5E"},
{name:"Brownie",age:"3 anos",sex:"M",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🍫",foto:"https://lh3.googleusercontent.com/d/105I2FO8C1gQtVGjSpfM1px0iShgGk8gO"},
{name:"Estela",age:"3 anos",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"✨",foto:"https://lh3.googleusercontent.com/d/1IzMWQ8Lo3nyeWASrucKMenwd--SVXZm_"},
{name:"Esmeralda",age:"4 anos",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"💚",foto:""},
{name:"Amora",age:"4 anos",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🫐",foto:"https://lh3.googleusercontent.com/d/1lUdChUg07QDivU9GGj7csfUVQRW4BKhc"},
{name:"Babuino",age:"3 anos",sex:"M",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🐒",foto:"https://lh3.googleusercontent.com/d/1lFxrG6xEoM-Ibr3X5mlE1BWzdRYmvMLL"},
{name:"Princesa",age:"3 anos",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"👸",foto:"https://lh3.googleusercontent.com/d/1D6Xu2hS59XipQjxQpXdj-3fFNQ5wkKG_"},
{name:"Catarina",age:"3 anos",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🦋",foto:"https://lh3.googleusercontent.com/d/1XNd8ALTA5wyOQg9Cq-ggf6EHArKyi_dX"},
{name:"Rebeca",age:"3 anos",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🌹",foto:"https://lh3.googleusercontent.com/d/1FB4rwlmhlCXetqaAGtnTbNuYmuuatmMg"},
{name:"Igor",age:"3 anos",sex:"M",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🎯",foto:"https://lh3.googleusercontent.com/d/1qYtvfDpTlmdn3wM1oCEIOdgRYvrD2oGe"},
{name:"Bianca",age:"3 anos",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🤍",foto:"https://lh3.googleusercontent.com/d/1B0tnByZcatcPg1Usvp6izk-1RXVjwt4Q"},
{name:"Gael",age:"3 anos",sex:"M",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🌊",foto:"https://lh3.googleusercontent.com/d/19bIODYtiZaec-nKCnZ7QPeivaLDGX1Xf"},
{name:"Brisa",age:"3 anos",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🍃",mascote:true,foto:"https://lh3.googleusercontent.com/d/1pFa_b7mG1q7P0k5TXTTDIAkBim_CX8V2"},
{name:"Ivy",age:"2 anos",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🌿",foto:"https://lh3.googleusercontent.com/d/1oHfLGzqnoXlsuGOwAL-WGUyEYSISvC-g"},
{name:"Emilia",age:"2 anos",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🎭",foto:"https://lh3.googleusercontent.com/d/1G4W7VgPnWfGjj8OnyJbBsCPMqdnA1dot"},
{name:"Sininho",age:"2 anos",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🔔",foto:"https://lh3.googleusercontent.com/d/15OFRztlSoHT769UwlzSDLJL8VWud01D5"},
{name:"Ariel",age:"2 anos",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🧜",foto:"https://lh3.googleusercontent.com/d/1DUa0cm6k7SqXRdaJ8uC-Ek3l0fBSJcAU"},
{name:"Tacha",age:"2 anos",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"📌",foto:"https://lh3.googleusercontent.com/d/1MT0LFZQFe49lHugTvYZPRT7Wm_zU-bEK"},
{name:"Romeu",age:"2 anos",sex:"M",castrated:true,vaccines:"V4+AR",condition:"",emoji:"💕",foto:"https://lh3.googleusercontent.com/d/1jSuypI318PXkyzjMJHDoFjJnxYJMM1bj"},
{name:"Joly",age:"2 anos",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🎪",foto:"https://lh3.googleusercontent.com/d/19txpp-GkpQukW_IBn-crbo43wZzEbl9m"},
{name:"Nutella",age:"2 anos",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🍫",foto:"https://lh3.googleusercontent.com/d/1pEk7LoGIDoiYapnhoRBhM3G8cD_HH24A"},
{name:"Tom",age:"2 anos",sex:"M",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🎵",foto:""},
{name:"Jojo",age:"1 ano",sex:"M",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🌀",foto:"https://lh3.googleusercontent.com/d/1UHMccnCb-umHlcsmcuMQhU6DqYkqV7Og"},
{name:"Pantufa",age:"1 ano",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🧦",foto:"https://lh3.googleusercontent.com/d/1uXaGCXPeCzcmH0xQq0jW7r5qcho7YV8u"},
{name:"Avelã",age:"1 ano",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🌰",foto:"https://lh3.googleusercontent.com/d/131PUMfVPvQ-24ndFtwzkZJ0dEPbp1pqH"},
{name:"Mônica",age:"1 ano",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"📘",foto:""},
{name:"Traquina",age:"1 ano",sex:"M",castrated:true,vaccines:"V4+AR",condition:"",emoji:"😈",foto:"https://lh3.googleusercontent.com/d/1q_itTi02PPJ_TWspvYXnJRAeRy99pSSC"},
{name:"Miguel",age:"1 ano",sex:"M",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🎩",foto:"https://lh3.googleusercontent.com/d/1XRyB4Mj4Gw5FxBymAWSlTqbRZRn1QMgW"},
{name:"Luck",age:"1 ano",sex:"M",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🍀",foto:"https://lh3.googleusercontent.com/d/1EzcHZSj7oBJgY0hvwMbq3MLxm2ZsVn1B"},
{name:"Nico",age:"1 ano",sex:"M",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🎲",foto:"https://lh3.googleusercontent.com/d/1dGWjsVy_ELQBLV43AY65Ks4016C-vSIR"},
{name:"Theo",age:"1 ano",sex:"M",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🧩",foto:"https://lh3.googleusercontent.com/d/1xxjEWUKK_pooiBan9n87JjeMzrpA_nTq"},
{name:"Boris",age:"Filhote",sex:"M",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🐻",foto:"https://lh3.googleusercontent.com/d/1q8vD-cIOyH_KbkLVe8RzpT1byTNnqJqN"},
{name:"Ziggy",age:"Filhote",sex:"M",castrated:true,vaccines:"V4+AR",condition:"",emoji:"⚡",foto:"https://lh3.googleusercontent.com/d/1ZXRHA1Ht_udkyUnGSv-pMywGii71sqBi"},
{name:"Safira",age:"Filhote",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"💙",foto:"https://lh3.googleusercontent.com/d/1V4tx9Y92TtKm6Jtm3e_8Di1V8gqFeTlK"},
{name:"Estrela",age:"1 ano",sex:"F",castrated:false,vaccines:"V4+AR",condition:"",emoji:"🌟",foto:""},
{name:"Cocada",age:"Filhote",sex:"M",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🥥",foto:"https://lh3.googleusercontent.com/d/1rSYJdHbxj-l58VdCQXdJ-rvJjxWWyZNZ"},
{name:"Alpino",age:"Filhote",sex:"M",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🏔️",foto:""},
{name:"Juma",age:"Filhote",sex:"M",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🐆",foto:""},
{name:"Luiza",age:"Filhote",sex:"F",castrated:false,vaccines:"V4+AR",condition:"Paraplégica",emoji:"🐯",mascote:true,foto:"https://lh3.googleusercontent.com/d/1xLo_kTH33M4tqNDwOBnurjU5gV7-97pB"},
{name:"Milk",age:"1 ano",sex:"M",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🥛",foto:"https://lh3.googleusercontent.com/d/1hc1nNBq6iUvxD12S9TmcRGKR-dQZs6TL"},
{name:"Pudim",age:"Filhote",sex:"M",castrated:false,vaccines:"V4+AR",condition:"",emoji:"🍮",foto:""},
{name:"Anne",age:"3 anos",sex:"F",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🌷",foto:"https://lh3.googleusercontent.com/d/1vLGWIckH346EREdcQ5Hd7Q1vNNYhzdTw"},
{name:"Tigrinho",age:"2 anos",sex:"M",castrated:true,vaccines:"V4+AR",condition:"",emoji:"🐅",foto:"https://lh3.googleusercontent.com/d/1zeR-wr6aDhefsEiNhN4FDVs5XnqXS-72"},
];
const MASCOTES=[{name:"Luiza",desc:"Tigrada elegante e paraplégica. Chegou filhote e hoje reina sobre a casa como se sempre tivesse sido dela.",emoji:"🐯"},{name:"Brisa",desc:"Tricolor e majestosa. Sobreviveu ao que não deveria ter sobrevivido e prova todos os dias que valeu a pena.",emoji:"🍃"}];
const EVENTS=[{date:"15 Fev",title:"Campanha Carnaval",desc:"Copos térmicos e combos especiais com desconto!",type:"venda",active:true},{date:"22 Fev",title:"Live: Conheça os Gatinhos",desc:"Tour virtual pela Casa dos Gatinhos no Instagram",type:"evento",active:true},{date:"01 Mar",title:"Prestação de Contas",desc:"Relatório financeiro aberto de fevereiro",type:"transparência",active:true},{date:"08 Mar",title:"Feira de Adoção",desc:"Encontre seu novo melhor amigo!",type:"adoção",active:false},{date:"15 Mar",title:"Bazar Solidário",desc:"Produtos da Casa dos Gatinhos + doações de parceiros",type:"venda",active:false}];
const PRODUCTS=[
{name:"Copo Térmico 600ml",price:60,impact:"Custeia 3 dias de ração para todos os gatinhos",emoji:"🥤",colors:["Rosa","Preto","Lilás","Verde","Branco"],status:"disponivel"},
{name:"Combo 2 Copos",price:110,impact:"1 semana de ração + economia de R$10",emoji:"🥤🥤",status:"disponivel"},
{name:"Combo 3 Copos",price:150,impact:"10 dias de ração + economia de R$30",emoji:"🎁",status:"disponivel"},
{name:"Ecobag Personalizada",price:35,impact:"1 consulta veterinária básica",emoji:"👜",status:"em_breve"},
{name:"Kit 3 Adesivos",price:18,impact:"1 dose de vermífugo",emoji:"✨",status:"em_breve"},
{name:"Combo Folião (Copo+Ecobag)",price:85,impact:"4 dias de ração + 1 consulta",emoji:"🎉",status:"em_breve"},
];
const SPONSOR_TIERS=[{name:"Amigo Felino",price:15,emoji:"🐱",color:"#F8B4C8",benefits:["Foto semanal do seu afilhado","Nome no mural digital","Grupo exclusivo WhatsApp"]},{name:"Protetor",price:30,emoji:"🛡️",color:"#E8548C",benefits:["Tudo do Amigo Felino","Vídeo mensal do gatinho","10% desconto na loja","Updates de saúde prioritários"]},{name:"Anjo Protetor",price:60,emoji:"👼",color:"#C41E5C",benefits:["Tudo do Protetor","Apadrinhamento nominal","Kit exclusivo anual","Visita à Casa","Certificado digital"]}];
const statusLabel={"disponivel":"Disponível","esgotado":"Esgotado","em_breve":"Em Breve"};
const statusStyle={"disponivel":{bg:"#D4EDDA",color:"#155724"},"esgotado":{bg:"#F8D7DA",color:"#721C24"},"em_breve":{bg:"#FFF3CD",color:"#856404"}};
function QRCodePix(){const qrUrl=`https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encodeURIComponent(PIX_KEY)}`;return(<div style={{textAlign:"center",padding:20}}><img src={qrUrl} alt="QR Code PIX" width={180} height={180} style={{borderRadius:12,border:"3px solid #E8548C"}}/><p style={{fontFamily:"'Nunito',sans-serif",fontSize:13,color:"#666",margin:"8px 0 0"}}>Escaneie para doar via PIX</p><p style={{fontFamily:"'Nunito',sans-serif",fontSize:14,fontWeight:800,color:"#E8548C",margin:"4px 0 0"}}>{PIX_KEY}</p></div>);}
function Nav({active,setActive}){const tabs=[{id:"home",label:"Início",icon:"🏠"},{id:"animals",label:"Nossos Gatos",icon:"🐱"},{id:"memorial",label:"In Memoriam",icon:"🕊️"},{id:"sponsor",label:"Seja Padrinho",icon:"💝"},{id:"shop",label:"Loja",icon:"🛍️"},{id:"events",label:"Eventos",icon:"📅"},{id:"transparency",label:"Contas",icon:"📊"}];return(<nav style={{position:"sticky",top:0,zIndex:100,background:"rgba(255,245,248,0.95)",backdropFilter:"blur(12px)",borderBottom:"2px solid #E8548C"}}><div style={{maxWidth:1100,margin:"0 auto",display:"flex",overflowX:"auto",gap:0}}>{tabs.map(t=>(<button key={t.id} onClick={()=>setActive(t.id)} style={{flex:"0 0 auto",padding:"12px 16px",border:"none",cursor:"pointer",background:active===t.id?"#E8548C":"transparent",color:active===t.id?"#fff":"#666",fontFamily:"'Nunito',sans-serif",fontWeight:active===t.id?800:600,fontSize:13,transition:"all 0.3s",whiteSpace:"nowrap",borderBottom:active===t.id?"3px solid #C41E5C":"3px solid transparent"}}><span style={{marginRight:4}}>{t.icon}</span>{t.label}</button>))}</div></nav>);}
function StatBadge({number,label}){return(<div style={{background:"rgba(255,255,255,0.85)",borderRadius:16,padding:"12px 20px",minWidth:100,backdropFilter:"blur(8px)"}}><div style={{fontFamily:"'Baloo 2',cursive",fontSize:24,color:"#E8548C",fontWeight:800}}>{number}</div><div style={{fontFamily:"'Nunito',sans-serif",fontSize:11,color:"#8B3A62",fontWeight:600}}>{label}</div></div>);}
function SectionTitle({emoji,title,subtitle}){return(<div style={{textAlign:"center",padding:"40px 24px 20px"}}><div style={{fontSize:36,marginBottom:8}}>{emoji}</div><h2 style={{fontFamily:"'Baloo 2',cursive",fontSize:32,color:"#C41E5C",margin:"0 0 6px"}}>{title}</h2>{subtitle&&<p style={{fontFamily:"'Nunito',sans-serif",fontSize:15,color:"#8B3A62",margin:0,opacity:0.8}}>{subtitle}</p>}</div>);}
function Hero(){const n=RESIDENTS.length,c=RESIDENTS.filter(r=>r.castrated).length;return(<div style={{background:"linear-gradient(135deg,#FFF5F8 0%,#FFE4ED 30%,#F8B4C8 70%,#E8548C 100%)",padding:"60px 24px 50px",textAlign:"center",position:"relative",overflow:"hidden"}}><div style={{position:"absolute",top:0,left:0,right:0,bottom:0,opacity:0.06,backgroundImage:"url(\"data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M30 10 C25 2 15 2 12 8 C9 14 18 18 30 28 C42 18 51 14 48 8 C45 2 35 2 30 10Z' fill='%23E8548C'/%3E%3C/svg%3E\")",backgroundSize:"60px 60px"}}/><div style={{position:"relative"}}><div style={{fontSize:64,marginBottom:8}}>🐱</div><h1 style={{fontFamily:"'Baloo 2',cursive",fontSize:"clamp(32px,6vw,52px)",color:"#C41E5C",margin:"0 0 8px",letterSpacing:-1}}>Casa dos Gatinhos</h1><p style={{fontFamily:"'Nunito',sans-serif",fontSize:18,color:"#8B3A62",maxWidth:500,margin:"0 auto 24px",lineHeight:1.5}}>Resgate. Cuidado. Dignidade.<br/><em style={{fontSize:15,opacity:0.8}}>Todo animal merece tratamento digno, independente da doença.</em></p><div style={{display:"flex",gap:12,justifyContent:"center",flexWrap:"wrap"}}><StatBadge number={`${n}`} label="Gatos residentes"/><StatBadge number={`R$${(META_MENSAL/1000).toFixed(1)}k`} label="Custo mensal"/><StatBadge number="200+" label="Apoiadores"/><StatBadge number={`${c}`} label="Castrados"/></div></div></div>);}
function InteractionSection(){const items=[{emoji:"📸",title:"Envie uma foto",desc:"Mande sua foto com produtos da Casa e apareça aqui!"},{emoji:"💬",title:"Sugira um nome",desc:"Próximo resgatado terá o nome escolhido pelos padrinhos!"},{emoji:"🎂",title:"Aniversários",desc:"Saiba quando é o aniversário do seu afilhado!"},{emoji:"🏥",title:"Boletim de saúde",desc:"Acompanhe a evolução clínica de cada animal"}];return(<div style={{padding:"30px 24px",background:"#FFF5F8"}}><h2 style={{fontFamily:"'Baloo 2',cursive",fontSize:26,color:"#E8548C",textAlign:"center",margin:"0 0 6px"}}>Interaja com os Gatinhos</h2><p style={{fontFamily:"'Nunito',sans-serif",fontSize:14,color:"#8B3A62",textAlign:"center",margin:"0 0 20px",opacity:0.7}}>Não é só doar — é fazer parte da família!</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(200px,1fr))",gap:12,maxWidth:900,margin:"0 auto"}}>{items.map(it=>(<div key={it.title} style={{background:"#fff",borderRadius:16,padding:20,textAlign:"center",boxShadow:"0 2px 10px rgba(232,84,140,0.06)"}}><div style={{fontSize:28,marginBottom:8}}>{it.emoji}</div><h3 style={{fontFamily:"'Nunito',sans-serif",fontSize:14,fontWeight:800,color:"#2D2D2D",margin:"0 0 4px"}}>{it.title}</h3><p style={{fontFamily:"'Nunito',sans-serif",fontSize:12,color:"#888",margin:0,lineHeight:1.4}}>{it.desc}</p></div>))}</div></div>);}
function AnimalCard({animal,onClick}){const condColors={"Paraplégica":"#9370DB"};const border=animal.condition?(condColors[animal.condition]||"#E8548C"):(animal.mascote?"#E8548C":"transparent");return(<div onClick={onClick} style={{background:animal.mascote?"#FFF0F5":"#fff",borderRadius:20,padding:0,cursor:"pointer",boxShadow:"0 4px 20px rgba(232,84,140,0.08)",border:`2px solid ${border}`,transition:"all 0.3s",minWidth:160,flex:"1 1 180px",maxWidth:220,position:"relative",overflow:"hidden"}} onMouseEnter={e=>{e.currentTarget.style.transform="translateY(-3px)";e.currentTarget.style.boxShadow="0 8px 25px rgba(232,84,140,0.15)"}} onMouseLeave={e=>{e.currentTarget.style.transform="translateY(0)";e.currentTarget.style.boxShadow="0 4px 20px rgba(232,84,140,0.08)"}}>{animal.mascote&&<div style={{position:"absolute",top:6,right:8,background:"#E8548C",color:"#fff",padding:"2px 8px",borderRadius:10,fontSize:9,fontWeight:800,zIndex:1}}>MASCOTE</div>}{animal.foto?<div style={{width:"100%",height:140,overflow:"hidden"}}><img src={animal.foto} alt={animal.name} style={{width:"100%",height:"100%",objectFit:"cover"}} onError={e=>{e.target.style.display="none";e.target.nextSibling.style.display="flex";}}/><div style={{width:"100%",height:"100%",display:"none",alignItems:"center",justifyContent:"center",background:"#FFF5F8",fontSize:48}}>{animal.emoji}</div></div>:<div style={{width:"100%",height:100,display:"flex",alignItems:"center",justifyContent:"center",background:"#FFF5F8",fontSize:48}}>{animal.emoji}</div>}<div style={{padding:"12px 18px 16px"}}><h3 style={{fontFamily:"'Baloo 2',cursive",fontSize:18,color:"#2D2D2D",margin:"0 0 2px"}}>{animal.name}</h3><div style={{fontFamily:"'Nunito',sans-serif",fontSize:11,color:"#888",marginBottom:4}}>{animal.sex==="F"?"♀ Fêmea":"♂ Macho"} · {animal.age}</div>{animal.condition&&<span style={{background:condColors[animal.condition]||"#E8548C",color:"#fff",padding:"2px 10px",borderRadius:10,fontSize:10,fontWeight:700}}>{animal.condition}</span>}<div style={{display:"flex",gap:4,marginTop:6,flexWrap:"wrap"}}>{animal.castrated&&<span style={{fontSize:9,background:"#E8F5E9",color:"#2E7D32",padding:"2px 6px",borderRadius:6}}>✓ Castrado</span>}<span style={{fontSize:9,background:"#E3F2FD",color:"#1565C0",padding:"2px 6px",borderRadius:6}}>💉 Vacinado</span></div></div></div>);}
function AnimalModal({animal,onClose}){if(!animal)return null;const waMsg=encodeURIComponent(`Olá! Quero apadrinhar o(a) ${animal.name} 🐱💝`);return(<div onClick={onClose} style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.5)",zIndex:200,display:"flex",alignItems:"center",justifyContent:"center",padding:20}}><div onClick={e=>e.stopPropagation()} style={{background:"#fff",borderRadius:24,padding:32,maxWidth:420,width:"100%",maxHeight:"80vh",overflow:"auto",position:"relative"}}><button onClick={onClose} style={{position:"absolute",top:12,right:16,background:"none",border:"none",fontSize:24,cursor:"pointer",color:"#999"}}>×</button><div style={{textAlign:"center",marginBottom:20}}>{animal.foto?<img src={animal.foto} alt={animal.name} style={{width:120,height:120,borderRadius:"50%",objectFit:"cover",border:"4px solid #E8548C",marginBottom:8}}/>:<div style={{fontSize:56,marginBottom:8}}>{animal.emoji}</div>}<h2 style={{fontFamily:"'Baloo 2',cursive",fontSize:28,color:"#C41E5C",margin:"0 0 4px"}}>{animal.name}</h2>{animal.mascote&&<span style={{background:"#E8548C",color:"#fff",padding:"3px 12px",borderRadius:20,fontSize:11,fontWeight:700}}>⭐ Mascote Oficial</span>}</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:16}}>{[["Sexo",animal.sex==="F"?"♀ Fêmea":"♂ Macho"],["Idade",animal.age],["Castrado",animal.castrated?"✅ Sim":"⏳ Pendente"],["Vacinas",animal.vaccines]].map(([l,v])=>(<div key={l} style={{background:"#F8F9FA",borderRadius:10,padding:"8px 12px"}}><div style={{fontFamily:"'Nunito',sans-serif",fontSize:10,color:"#999",fontWeight:700,marginBottom:2}}>{l}</div><div style={{fontFamily:"'Nunito',sans-serif",fontSize:13,color:"#333",fontWeight:600}}>{v}</div></div>))}</div>{animal.condition&&<div style={{background:"#FFF3E0",borderRadius:12,padding:12,marginBottom:16,textAlign:"center"}}><span style={{fontFamily:"'Nunito',sans-serif",fontSize:13,fontWeight:800,color:"#E65100"}}>⚕️ Condição: {animal.condition}</span></div>}<div style={{textAlign:"center",marginTop:16}}><a href={`https://wa.me/${WHATSAPP}?text=${waMsg}`} target="_blank" rel="noreferrer" style={{display:"inline-block",background:"linear-gradient(135deg,#E8548C,#C41E5C)",color:"#fff",borderRadius:30,padding:"14px 36px",fontFamily:"'Nunito',sans-serif",fontSize:16,fontWeight:800,textDecoration:"none",boxShadow:"0 4px 15px rgba(232,84,140,0.3)"}}>💝 Apadrinhar {animal.name}</a><div style={{marginTop:10}}><span style={{fontFamily:"'Nunito',sans-serif",fontSize:12,color:"#888"}}>PIX: {PIX_KEY}</span></div></div></div></div>);}
function MemorialSection(){const[expanded,setExpanded]=useState(null);return(<div style={{background:"linear-gradient(180deg,#1a1a2e 0%,#16213e 100%)",padding:"0 0 50px"}}><div style={{textAlign:"center",padding:"40px 24px 20px"}}><div style={{fontSize:36,marginBottom:8}}>🕊️</div><h2 style={{fontFamily:"'Baloo 2',cursive",fontSize:32,color:"#F8B4C8",margin:"0 0 6px"}}>In Memoriam</h2><p style={{fontFamily:"'Nunito',sans-serif",fontSize:15,color:"rgba(255,255,255,0.6)",margin:"0 0 8px"}}>Eles partiram, mas suas histórias continuam salvando vidas.</p><p style={{fontFamily:"'Nunito',sans-serif",fontSize:13,color:"rgba(255,255,255,0.4)",fontStyle:"italic",maxWidth:500,margin:"0 auto"}}>A investigação dos prontuários destes animais revelou a ausência de rastreamento de tratamento — e mudou para sempre a forma como a Casa dos Gatinhos cuida de seus protegidos.</p></div><div style={{maxWidth:800,margin:"0 auto",padding:"0 24px"}}>{MEMORIAL.map((m,i)=>(<div key={m.name} onClick={()=>setExpanded(expanded===i?null:i)} style={{background:expanded===i?"rgba(255,255,255,0.08)":"rgba(255,255,255,0.03)",borderRadius:16,padding:"20px 24px",marginBottom:12,cursor:"pointer",borderLeft:`4px solid ${m.color}`,transition:"all 0.3s"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><span style={{fontSize:20,marginRight:8}}>{m.emoji}</span><span style={{fontFamily:"'Baloo 2',cursive",fontSize:20,color:m.color}}>{m.name}</span>{m.dates&&<span style={{fontFamily:"'Nunito',sans-serif",fontSize:11,color:"rgba(255,255,255,0.3)",marginLeft:10}}>{m.dates}</span>}</div><span style={{color:"rgba(255,255,255,0.3)",fontSize:20,transition:"transform 0.3s",transform:expanded===i?"rotate(180deg)":"rotate(0)"}}>▼</span></div>{expanded===i&&(<div style={{marginTop:16,animation:"fadeIn 0.3s ease"}}><p style={{fontFamily:"'Nunito',sans-serif",fontSize:14,color:"rgba(255,255,255,0.8)",lineHeight:1.6,margin:"0 0 12px"}}>{m.story}</p><div style={{background:"rgba(255,255,255,0.05)",borderRadius:10,padding:12}}><p style={{fontFamily:"'Nunito',sans-serif",fontSize:12,color:"rgba(255,255,255,0.5)",margin:0}}><strong style={{color:m.color}}>Causa:</strong> {m.cause}</p></div></div>)}</div>))}</div><div style={{textAlign:"center",marginTop:24}}><p style={{fontFamily:"'Nunito',sans-serif",fontSize:14,color:"rgba(255,255,255,0.4)",fontStyle:"italic"}}>&quot;Resistir aos vírus depende do organismo. Direito ao tratamento digno, não.&quot;</p></div></div>);}
function SponsorSection(){return(<div style={{background:"linear-gradient(135deg,#FFF5F8 0%,#FFE4ED 100%)",padding:"0 0 50px"}}><SectionTitle emoji="💝" title="Seja Padrinho" subtitle="Escolha como fazer parte da vida de um gatinho"/><div style={{textAlign:"center",marginBottom:20}}><div style={{background:"#fff",display:"inline-block",borderRadius:16,padding:"12px 24px",boxShadow:"0 2px 10px rgba(0,0,0,0.06)"}}><span style={{fontFamily:"'Nunito',sans-serif",fontSize:13,color:"#888"}}>Padrinhos ativos: </span><span style={{fontFamily:"'Baloo 2',cursive",fontSize:20,color:"#E8548C"}}>1</span><span style={{fontFamily:"'Nunito',sans-serif",fontSize:13,color:"#888"}}> · R$ 1.008/mês</span></div></div><div style={{display:"flex",gap:20,flexWrap:"wrap",justifyContent:"center",padding:"0 24px",maxWidth:900,margin:"0 auto"}}>{SPONSOR_TIERS.map((tier,i)=>(<div key={tier.name} style={{background:"#fff",borderRadius:24,padding:28,flex:"1 1 250px",maxWidth:280,boxShadow:i===1?"0 8px 40px rgba(232,84,140,0.2)":"0 4px 20px rgba(0,0,0,0.06)",border:i===1?"3px solid #E8548C":"2px solid #f0f0f0",transform:i===1?"scale(1.04)":"scale(1)",position:"relative"}}>{i===1&&<div style={{position:"absolute",top:-12,left:"50%",transform:"translateX(-50%)",background:"#E8548C",color:"#fff",padding:"4px 16px",borderRadius:20,fontSize:11,fontWeight:800}}>MAIS POPULAR</div>}<div style={{textAlign:"center",marginBottom:16}}><div style={{fontSize:40,marginBottom:8}}>{tier.emoji}</div><h3 style={{fontFamily:"'Baloo 2',cursive",fontSize:22,color:tier.color,margin:"0 0 4px"}}>{tier.name}</h3><div style={{fontFamily:"'Baloo 2',cursive",fontSize:32,color:"#2D2D2D"}}>R$ {tier.price}<span style={{fontSize:14,color:"#999",fontWeight:400}}>/mês</span></div></div><ul style={{listStyle:"none",padding:0,margin:"0 0 20px"}}>{tier.benefits.map((b,j)=>(<li key={j} style={{fontFamily:"'Nunito',sans-serif",fontSize:13,color:"#555",padding:"6px 0",borderBottom:"1px solid #f5f5f5",display:"flex",gap:8}}><span style={{color:"#E8548C",flexShrink:0}}>✓</span>{b}</li>))}</ul><a href={`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(`Olá! Quero ser ${tier.name} da Casa dos Gatinhos 💝`)}`} target="_blank" rel="noreferrer" style={{display:"block",width:"100%",background:`linear-gradient(135deg,${tier.color},${tier.color}dd)`,color:"#fff",border:"none",borderRadius:14,padding:"12px 0",fontFamily:"'Nunito',sans-serif",fontSize:15,fontWeight:800,cursor:"pointer",boxShadow:`0 4px 15px ${tier.color}40`,textAlign:"center",textDecoration:"none"}}>Quero ser {tier.name}</a></div>))}</div><QRCodePix/></div>);}
function ShopSection(){return(<div style={{padding:"0 0 50px",background:"#fff"}}><SectionTitle emoji="🛍️" title="Loja Solidária" subtitle="Cada produto vendido sustenta a Casa dos Gatinhos"/><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(280px,1fr))",gap:16,padding:"0 24px",maxWidth:900,margin:"0 auto"}}>{PRODUCTS.map(p=>{const st=statusStyle[p.status]||statusStyle.disponivel;const isAvail=p.status==="disponivel";const waMsg=encodeURIComponent(`Olá! Quero comprar: ${p.name} - R$ ${p.price}\nCasa dos Gatinhos 🐱`);return(<div key={p.name} style={{background:"#FFF5F8",borderRadius:20,padding:20,display:"flex",flexDirection:"column",opacity:isAvail?1:0.8}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"start",marginBottom:12}}><span style={{fontSize:32}}>{p.emoji}</span><div style={{textAlign:"right"}}><span style={{fontFamily:"'Baloo 2',cursive",fontSize:24,color:"#E8548C"}}>R$ {p.price}</span><div><span style={{background:st.bg,color:st.color,padding:"2px 10px",borderRadius:10,fontSize:10,fontWeight:700}}>{statusLabel[p.status]}</span></div></div></div><h3 style={{fontFamily:"'Nunito',sans-serif",fontSize:16,fontWeight:800,color:"#2D2D2D",margin:"0 0 6px"}}>{p.name}</h3><p style={{fontFamily:"'Nunito',sans-serif",fontSize:12,color:"#888",margin:"0 0 12px",lineHeight:1.4,flex:1}}><span style={{color:"#E8548C",fontWeight:700}}>Impacto:</span> {p.impact}</p>{p.colors&&p.colors.length>0&&<div style={{display:"flex",gap:4,marginBottom:12,flexWrap:"wrap"}}>{p.colors.map(c=><span key={c} style={{fontSize:10,background:"#fff",padding:"2px 8px",borderRadius:10,color:"#666"}}>{c}</span>)}</div>}{isAvail?<div style={{display:"flex",gap:8}}><a href={`https://wa.me/${WHATSAPP}?text=${waMsg}`} target="_blank" rel="noreferrer" style={{flex:1,background:"#25D366",color:"#fff",border:"none",borderRadius:12,padding:"10px 0",fontFamily:"'Nunito',sans-serif",fontSize:13,fontWeight:700,textAlign:"center",textDecoration:"none"}}>💬 WhatsApp</a><a href={`mailto:${PIX_KEY}?subject=Pedido: ${p.name}&body=Olá! Quero comprar: ${p.name} - R$ ${p.price}`} style={{flex:1,background:"#E8548C",color:"#fff",border:"none",borderRadius:12,padding:"10px 0",fontFamily:"'Nunito',sans-serif",fontSize:13,fontWeight:700,textAlign:"center",textDecoration:"none"}}>📧 E-mail</a></div>:<div style={{background:"#eee",borderRadius:12,padding:"10px 0",textAlign:"center",fontFamily:"'Nunito',sans-serif",fontSize:13,fontWeight:700,color:"#999"}}>{p.status==="esgotado"?"Esgotado 😿":"Em Breve 🔜"}</div>}</div>)})}</div><QRCodePix/></div>);}
function EventsSection(){const tc={venda:"#E8548C",evento:"#4A90D9","transparência":"#2E8B57","adoção":"#F4A460"};return(<div style={{padding:"0 0 50px",background:"#FAFAFA"}}><SectionTitle emoji="📅" title="Eventos & Campanhas" subtitle="Participe, compre, ajude, interaja!"/><div style={{maxWidth:700,margin:"0 auto",padding:"0 24px"}}>{EVENTS.map((e,i)=>(<div key={i} style={{display:"flex",gap:16,padding:20,marginBottom:12,background:e.active?"#fff":"#f5f5f5",borderRadius:16,border:e.active?`2px solid ${tc[e.type]}`:"2px solid #e0e0e0",opacity:e.active?1:0.6}}><div style={{minWidth:60,textAlign:"center"}}><div style={{fontFamily:"'Baloo 2',cursive",fontSize:18,color:tc[e.type],fontWeight:800}}>{e.date.split(" ")[0]}</div><div style={{fontFamily:"'Nunito',sans-serif",fontSize:11,color:"#999"}}>{e.date.split(" ")[1]}</div></div><div style={{flex:1}}><div style={{display:"flex",gap:8,alignItems:"center",marginBottom:4,flexWrap:"wrap"}}><h3 style={{fontFamily:"'Nunito',sans-serif",fontSize:16,fontWeight:800,color:"#2D2D2D",margin:0}}>{e.title}</h3><span style={{background:tc[e.type],color:"#fff",padding:"2px 8px",borderRadius:10,fontSize:10,fontWeight:700}}>{e.type}</span>{e.active&&<span style={{background:"#2E8B57",color:"#fff",padding:"2px 8px",borderRadius:10,fontSize:10,fontWeight:700}}>ATIVO</span>}</div><p style={{fontFamily:"'Nunito',sans-serif",fontSize:13,color:"#666",margin:0}}>{e.desc}</p></div></div>))}</div></div>);}
function TransparencySection(){const n=RESIDENTS.length;const cats=[{name:"Aluguel",value:2832,pct:41},{name:"Ração e alimentação",value:2101,pct:31},{name:"Vacinas e medicamentos",value:1083,pct:16},{name:"Energia e água",value:412,pct:6},{name:"Limpeza e higiene",value:452,pct:6}];const total=cats.reduce((s,c)=>s+c.value,0);const bc=["#E8548C","#F8B4C8","#C41E5C","#9370DB","#4ECDC4"];return(<div style={{padding:"0 0 50px",background:"#fff"}}><SectionTitle emoji="📊" title="Prestação de Contas" subtitle="Transparência total — cada centavo importa"/><div style={{maxWidth:700,margin:"0 auto",padding:"0 24px"}}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(150px,1fr))",gap:12,marginBottom:24}}>{[["GATOS ATIVOS",n,"#E8548C"],["CUSTO MENSAL",`R$ ${total.toLocaleString()}`,"#C41E5C"],["ENTRADAS",`R$ 1.008`,"#2E8B57"],["DÉFICIT",`-R$ ${(total-1008).toLocaleString()}`,"#FF6B6B"]].map(([l,v,c])=>(<div key={l} style={{background:"#FFF5F8",borderRadius:16,padding:20,textAlign:"center"}}><div style={{fontFamily:"'Nunito',sans-serif",fontSize:11,color:"#999",fontWeight:700}}>{l}</div><div style={{fontFamily:"'Baloo 2',cursive",fontSize:28,color:c}}>{v}</div></div>))}</div><div style={{background:"#FFF5F8",borderRadius:20,padding:24,marginBottom:24}}><h3 style={{fontFamily:"'Nunito',sans-serif",fontSize:14,fontWeight:800,color:"#E8548C",margin:"0 0 16px"}}>GASTOS MENSAIS POR CATEGORIA</h3>{cats.map((c,i)=>(<div key={c.name} style={{marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:4}}><span style={{fontFamily:"'Nunito',sans-serif",fontSize:13,color:"#444"}}>{c.name}</span><span style={{fontFamily:"'Nunito',sans-serif",fontSize:13,color:"#666",fontWeight:700}}>R$ {c.value.toLocaleString()} ({c.pct}%)</span></div><div style={{background:"#f0f0f0",borderRadius:6,height:10,overflow:"hidden"}}><div style={{background:bc[i],width:`${c.pct}%`,height:"100%",borderRadius:6,transition:"width 0.8s ease"}}/></div></div>))}<div style={{borderTop:"2px solid #E8548C",marginTop:16,paddingTop:12,display:"flex",justifyContent:"space-between"}}><span style={{fontFamily:"'Nunito',sans-serif",fontSize:15,fontWeight:800,color:"#C41E5C"}}>TOTAL MENSAL</span><span style={{fontFamily:"'Baloo 2',cursive",fontSize:22,color:"#C41E5C"}}>R$ {total.toLocaleString()}</span></div></div><div style={{background:"linear-gradient(135deg,#E8548C,#C41E5C)",borderRadius:20,padding:28,textAlign:"center",color:"#fff"}}><h3 style={{fontFamily:"'Baloo 2',cursive",fontSize:22,margin:"0 0 8px"}}>Faça a diferença</h3><p style={{fontFamily:"'Nunito',sans-serif",fontSize:14,margin:"0 0 4px",opacity:0.9}}>Se cada um dos 200+ apoiadores contribuir com <strong>R$ {Math.round(total/200)}/mês</strong>, cobrimos todas as despesas.</p><p style={{fontFamily:"'Nunito',sans-serif",fontSize:16,margin:"12px 0 0",fontWeight:800}}>PIX: {PIX_KEY}</p></div><QRCodePix/></div></div>);}
function CtaBar(){return(<div style={{position:"fixed",bottom:0,left:0,right:0,zIndex:100,background:"linear-gradient(135deg,#E8548C,#C41E5C)",padding:"12px 24px",display:"flex",justifyContent:"center",gap:12,alignItems:"center",boxShadow:"0 -4px 20px rgba(0,0,0,0.15)"}}><a href={`https://wa.me/${WHATSAPP}?text=${encodeURIComponent("Olá! Quero comprar produtos da Casa dos Gatinhos 🐱")}`} target="_blank" rel="noreferrer" style={{background:"#fff",color:"#E8548C",border:"none",borderRadius:25,padding:"10px 24px",fontFamily:"'Nunito',sans-serif",fontSize:14,fontWeight:800,cursor:"pointer",textDecoration:"none"}}>🛍️ Loja</a><a href={`https://wa.me/${WHATSAPP}?text=${encodeURIComponent("Olá! Quero apadrinhar um gatinho da Casa dos Gatinhos 💝")}`} target="_blank" rel="noreferrer" style={{background:"rgba(255,255,255,0.15)",color:"#fff",border:"2px solid rgba(255,255,255,0.4)",borderRadius:25,padding:"10px 24px",fontFamily:"'Nunito',sans-serif",fontSize:14,fontWeight:800,cursor:"pointer",textDecoration:"none"}}>💝 Apadrinhar</a><button onClick={()=>{navigator.clipboard&&navigator.clipboard.writeText(PIX_KEY);alert("PIX copiado: "+PIX_KEY)}} style={{background:"rgba(255,255,255,0.15)",color:"#fff",border:"2px solid rgba(255,255,255,0.4)",borderRadius:25,padding:"10px 24px",fontFamily:"'Nunito',sans-serif",fontSize:14,fontWeight:800,cursor:"pointer"}}>PIX Direto</button></div>);}
function Footer(){return(<footer style={{background:"#1a1a2e",padding:"40px 24px 80px",textAlign:"center"}}><div style={{fontSize:36,marginBottom:12}}>🐱</div><h3 style={{fontFamily:"'Baloo 2',cursive",fontSize:24,color:"#F8B4C8",margin:"0 0 8px"}}>Casa dos Gatinhos</h3><p style={{fontFamily:"'Nunito',sans-serif",fontSize:13,color:"rgba(255,255,255,0.5)",maxWidth:400,margin:"0 auto 16px"}}>Resgate, cuidado e dignidade para cada animal. Porque nenhum gato deveria sofrer sozinho.</p><div style={{display:"flex",gap:12,justifyContent:"center",marginBottom:16}}><a href={INSTAGRAM} target="_blank" rel="noreferrer" style={{background:"rgba(255,255,255,0.1)",color:"#F8B4C8",padding:"8px 16px",borderRadius:20,textDecoration:"none",fontFamily:"'Nunito',sans-serif",fontSize:13,fontWeight:700}}>📸 Instagram</a><a href={`https://wa.me/${WHATSAPP}`} target="_blank" rel="noreferrer" style={{background:"rgba(255,255,255,0.1)",color:"#F8B4C8",padding:"8px 16px",borderRadius:20,textDecoration:"none",fontFamily:"'Nunito',sans-serif",fontSize:13,fontWeight:700}}>💬 WhatsApp</a></div><p style={{fontFamily:"'Nunito',sans-serif",fontSize:12,color:"rgba(255,255,255,0.4)",marginBottom:4}}>PIX: {PIX_KEY}</p><p style={{fontFamily:"'Nunito',sans-serif",fontSize:11,color:"rgba(255,255,255,0.3)"}}>Em memória de Vitória 👑 Sucrilhos 🌟 Ozzy 🎸 Chico 🍀 Bernardo 💙</p><a href="/admin" style={{display:"inline-block",marginTop:12,fontSize:10,color:"rgba(255,255,255,0.15)",textDecoration:"none"}}>⚙️</a></footer>);}
export default function App(){const[active,setActive]=useState("home");const[selectedAnimal,setSelectedAnimal]=useState(null);const[filter,setFilter]=useState("all");const[search,setSearch]=useState("");const filtered=RESIDENTS.filter(r=>{if(filter==="mascote")return r.mascote;if(filter==="condition")return r.condition;if(filter==="female")return r.sex==="F";if(filter==="male")return r.sex==="M";return true}).filter(r=>search?r.name.toLowerCase().includes(search.toLowerCase()):true);return(<div style={{fontFamily:"'Nunito',sans-serif",minHeight:"100vh",background:"#fff"}}><Head><title>Casa dos Gatinhos — Resgate, Cuidado e Dignidade</title><meta name="description" content="Projeto de proteção animal com 59 gatos resgatados. Apadrinhe, doe, faça parte. PIX: casadosgatinhos22@gmail.com"/><meta name="viewport" content="width=device-width, initial-scale=1"/><meta property="og:title" content="Casa dos Gatinhos"/><meta property="og:description" content="59 gatos resgatados precisam de você. Todo animal merece tratamento digno."/><meta property="og:type" content="website"/><link rel="preconnect" href="https://fonts.googleapis.com"/><link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/><link href="https://fonts.googleapis.com/css2?family=Baloo+2:wght@400;600;700;800&family=Nunito:ital,wght@0,400;0,600;0,700;0,800;1,400&display=swap" rel="stylesheet"/></Head><style>{`*{box-sizing:border-box;margin:0;padding:0}body{overflow-x:hidden}@keyframes fadeIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}::-webkit-scrollbar{height:4px}::-webkit-scrollbar-track{background:transparent}::-webkit-scrollbar-thumb{background:#E8548C;border-radius:4px}`}</style><Nav active={active} setActive={setActive}/>
{active==="home"&&(<><Hero/><InteractionSection/><div style={{padding:"30px 24px",background:"#fff",textAlign:"center"}}><h2 style={{fontFamily:"'Baloo 2',cursive",fontSize:26,color:"#C41E5C",margin:"0 0 6px"}}>⭐ Nossos Mascotes</h2><p style={{fontFamily:"'Nunito',sans-serif",fontSize:14,color:"#8B3A62",margin:"0 0 16px",opacity:0.7}}>Os embaixadores da Casa dos Gatinhos</p><div style={{display:"flex",gap:16,justifyContent:"center",flexWrap:"wrap"}}>{MASCOTES.map(m=>(<div key={m.name} style={{background:"#FFF0F5",borderRadius:20,padding:24,flex:"1 1 250px",maxWidth:300,border:"2px solid #E8548C"}}><div style={{fontSize:48,marginBottom:8}}>{m.emoji}</div><h3 style={{fontFamily:"'Baloo 2',cursive",fontSize:22,color:"#C41E5C",margin:"0 0 6px"}}>{m.name}</h3><p style={{fontFamily:"'Nunito',sans-serif",fontSize:13,color:"#666",lineHeight:1.5}}>{m.desc}</p></div>))}</div></div><div style={{padding:"0 0 20px",background:"#fff"}}><SectionTitle emoji="🐱" title="Conheça Nossos Gatinhos" subtitle={`${RESIDENTS.length} gatos resgatados vivendo com dignidade`}/><div style={{display:"flex",gap:12,flexWrap:"wrap",justifyContent:"center",padding:"0 24px",maxWidth:1000,margin:"0 auto"}}>{RESIDENTS.filter(r=>r.mascote||r.condition).concat(RESIDENTS.filter(r=>!r.mascote&&!r.condition).slice(0,4)).slice(0,6).map(a=><AnimalCard key={a.name} animal={a} onClick={()=>setSelectedAnimal(a)}/>)}</div><div style={{textAlign:"center",marginTop:16}}><button onClick={()=>setActive("animals")} style={{background:"none",border:"2px solid #E8548C",color:"#E8548C",borderRadius:25,padding:"10px 28px",fontFamily:"'Nunito',sans-serif",fontSize:14,fontWeight:700,cursor:"pointer"}}>Ver todos os {RESIDENTS.length} gatinhos →</button></div></div><QRCodePix/></>)}
{active==="animals"&&(<div style={{padding:"0 0 50px"}}><SectionTitle emoji="🐱" title="Nossos Gatinhos" subtitle={`${RESIDENTS.length} gatos resgatados — cada um com sua história`}/><div style={{maxWidth:1000,margin:"0 auto 20px",padding:"0 24px",display:"flex",gap:8,flexWrap:"wrap",justifyContent:"center",alignItems:"center"}}><input placeholder="🔍 Buscar por nome..." value={search} onChange={e=>setSearch(e.target.value)} style={{padding:"8px 16px",borderRadius:20,border:"2px solid #E8548C",fontFamily:"'Nunito',sans-serif",fontSize:13,outline:"none",width:200}}/>{[{id:"all",label:`Todos (${RESIDENTS.length})`},{id:"mascote",label:"⭐ Mascotes"},{id:"condition",label:"⚕️ Especiais"},{id:"female",label:`♀ Fêmeas (${RESIDENTS.filter(r=>r.sex==="F").length})`},{id:"male",label:`♂ Machos (${RESIDENTS.filter(r=>r.sex==="M").length})`}].map(f=>(<button key={f.id} onClick={()=>setFilter(f.id)} style={{padding:"6px 14px",borderRadius:16,border:"none",cursor:"pointer",background:filter===f.id?"#E8548C":"#f0f0f0",color:filter===f.id?"#fff":"#666",fontFamily:"'Nunito',sans-serif",fontSize:12,fontWeight:700}}>{f.label}</button>))}</div><div style={{display:"flex",gap:12,flexWrap:"wrap",justifyContent:"center",padding:"0 24px",maxWidth:1100,margin:"0 auto"}}>{filtered.map(a=><AnimalCard key={a.name} animal={a} onClick={()=>setSelectedAnimal(a)}/>)}</div>{filtered.length===0&&<p style={{textAlign:"center",color:"#999",padding:40}}>Nenhum gatinho encontrado.</p>}</div>)}
{active==="memorial"&&<MemorialSection/>}{active==="sponsor"&&<SponsorSection/>}{active==="shop"&&<ShopSection/>}{active==="events"&&<EventsSection/>}{active==="transparency"&&<TransparencySection/>}<Footer/><CtaBar/>{selectedAnimal&&<AnimalModal animal={selectedAnimal} onClose={()=>setSelectedAnimal(null)}/>}</div>);}
